### ISSUE TITLE
Retire OpenStax College servers and code

### ISSUE THREAD

**Issue by jpslav** [openstax/os-webview#1291]
### Description
The old openstaxcollege.org site is still running so that links to it that remain in the hands of our users still work.  This includes "short code" links from our books, e.g. https://www.openstaxcollege.org/l/24polydivision2 so of which are embedded in QR codes in our books.  

The OpenStax College servers mostly redirect all requests to OpenStax.org; this includes short codes and errata links.  The traffic to openstax.org that came from openstaxcollege.org represented 0.2% of the total openstax.org traffic in October of 2018 (per Google Analytics).

Some links, like https://www.openstaxcollege.org/pages/uhdowntown_macro are still served by the OSC servers.  Hopefully links like this can be turned into redirects.

We should implement a solution that handles all of these redirects without requiring us to keep a couple of servers running on AWS.  These servers cost around $300 per month and they don't get security updates so they are increasingly at risk for getting hacked.  Getting rid of these servers will also let us archive old private code repositories on Github.

A solution that will let us keep these openstaxcollege.org links alive and let us retire these servers and code would be to use a CloudFront distribution with Lambda@Edge functions handling redirects.

The steps would be to:
1. Write a Lambda@Edge function in Python that handles the redirect logic currently handled by NGINX running on the OSC servers.
2. Make a CloudFront distribution with an origin that is the OSWeb site.  Whenever a request was made to the distribution that was not cached, the distribution would trigger the lambda function (via an "origin request" trigger) and the user would get redirected to the right place on openstax.org.  All requests that we don't have a redirect mapping for could be redirected to some generic page on openstax.org.
3. Set up SSL (using the Amazon Certificate Manager)
4. Point the openstaxcollege.org domain to this CloudFront distribution.
5. Take down the OSC servers
6. Archive the old OSC code on Github.
7. Celebrate.

In October there were 212 requests to openstaxcollege.org (that we know of via Google Analytics).  The CloudFront solution would cost a penny per month and would require no upkeep.

Preliminaries:
1. Figure out if the links still hosted by OSC can be redirected somewhere on openstax.org or if they can just be abandoned.

Alternatives: 
* Leadership could decide not to worry about the 212 visitors per month and just retire the servers and redirect all openstaxcollege.org traffic to the openstax.org domain.

**Comment by openstaxalina** [comment]
@jpslav I agree with this, specifically:
`We should implement a solution that handles all of these redirects without requiring us to keep a couple of servers running on AWS. These servers cost around $300 per month and they don't get security updates so they are increasingly at risk for getting hacked. Getting rid of these servers will also let us archive old private code repositories on Github.`

**Content update:** We've changed all instances of `openstaxcollege.org/l` to `openstax.org/l` in our books on cnx.org.  _rHowever, **most** of the PDFs still have many instances of `openstaxcollege.org/l`, because the PDFs are updated less regularly.  So, I agree that it is crucial those redirects continue to work.

--- 
(probably less pertinent...)
Amazon detected degraded hardware for openstaxcollege.org in March 2018.  Amazon decommissioned the instance (_I think_). All the redirects stopped working, I guess because we didn't have CloudFront distribution or anything similar in place.  
The issue started here: https://openstax.slack.com/archives/C0F5DE456/p1522098480000484
...and ended, from what I can tell, here: https://openstax.slack.com/archives/C0F5DE456/p1522103188000050

All this to say...we received errata reports about the broken links within hours, so my main concern is avoiding that situation in the future.
