### ISSUE TITLE
REX > Book Details page path needs a loading state

### ISSUE THREAD

**Issue by kjdav** [openstax/os-webview#1589]
When you click < [Book name] from a REX page, it takes a few seconds to load the book details page. 

Can OSweb show a loading state for this case?

Suggested a/c for this but obviously up to Allison: 

given you're looking at a rex page on desktop (e.g., https://openstax.org/books/calculus-volume-1/pages/1-introduction) 
and you click < [book name] 
then you are taken to the book page for that book (e.g., https://openstax.org/details/books/calculus-volume-1)
and if the book page takes longer than x seconds to load a loading graphic is shown
then the book details page is loaded

**Comment by RoyEJohnson** [comment]
The problem is that most of the delay is due to loading the foundations of the site, which has to load before the loading screen will display. The specific page information is loading very fast, by comparison, which is why you don't see the loader (the details page does have a loader that displays until the page builds).

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.

**Comment by kjdav** [comment]
Hey can you describe when the loading state should appear? I don't see it, but maybe my page loads too fast. cc @Brooke-Fail

**Comment by RoyEJohnson** [comment]
The best way to see it is to set your browser to be throttled. In the Network tab on Chrome there's a  dropdown that says "Online" and you can select "Fast 3G".
