### ISSUE TITLE
"Log in to unlock" is confusing for rejected but logged in instructors

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#1975]
# Description
Instructor resources either present a link if you are a logged in, verified instructor, or say "Log in to unlock" otherwise. Logged-in people see that message when they are not verified instructors. That could be confusing.

UX should recommend messaging for logged-in people who don't have access.
Roy should put it in.

# Acceptance Tests
- [ ] Instructor resources have "Only available for verified instructors" when logged in as a pending or rejected instructor
- [ ] they say "Login to unlock" when not logged in
- [ ] they allow Download when logged in and verified
- [ ] UX review

**Comment by butlerst** [comment]
Design solution:

https://www.figma.com/file/VSwXNFfiHYtz0SJx9bNF8I/BIT_MyOpenStax_RejectedInstructors?node-id=161%3A0

We felt there should be a way for rejected instructors to be able to contact support, so that they didn't feel like they had reached a complete dead end, unable to access resources. That resulted in this design, linked above. Desktop and mobile screens both included. The "comment" tab calls out the main changes. Let me know if you have any questions!

@RoyEJohnson

**Comment by RoyEJohnson** [comment]
![image.png](https://images.zenhubusercontent.com/5bacf5c2179f09585770fba9/0c998f9e-b1ad-486d-852e-9d1e7211606c)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
