### ISSUE TITLE
New "All Subjects" page

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/os-webview#2130]
# Description
[Design](https://www.figma.com/file/lIFpeQZeCcuj9p1yLHVurT/Subjects?node-id=352%3A469)

- Hero
- Language selector
- Subjects listing
- Tutor ad block
- About OpenStax textbooks
- Info boxes
- Philanthropic support 

## Data issues
- Spanish version of page
- Translations per subject category

**Comment by dkhowala** [comment]
Reviewed the page on Staging.
The page currently has placeholders for icons and images which makes it difficult to do a thorough review.
It will be better if I do a functional review of the page when it is as close to the original as possible.

Few things I noticed:

The page heading " browse our subjects" should be in sentence case.
Who is responsible for the final copy? some of it seems yet to be decided or is different from Sarah's design.
The subject order should be the same as in the design.
What is the logic behind the booklist order? An alphabetical order list allows for easier browsing. (This is a new request, so we can tackle it separately.)
Another new request, please change the font-weight of View all.... to bold or semibold so that users can distinguish it from other book links.
College success has only one book so it will not have the" view all" option.
In the ' instructors, take your course online' box, the spacing, and X and Y coordinates of the text are off.
The size of the cards is incorrect. The content is fixed to include an icon, heading, and body text. I don't see a future use case for images.
In the philanthropic sentence, the bold and regular text doesn't match the original design.

**Comment by ltjosephs** [comment]
Tasks still needed to be completed:

**Comment by brittanyearly** [comment]
Needs to be tested in Staging.

**Comment by DominiqueShu** [comment]
Setting up review meeting w Lindsay, Roy and Ed for next steps.

**Comment by mwvolo** [comment]
I'm closing this card -- if there are any issues with the subjects page, please reopen a card with the requirements needed and any deadlines for the new subjects page feature flag listed.
